### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by robinweser** [robinweser/fela#615]
**Type**:  Docs

-------------------
#### Description
It's time to go through the docs and improve the once again.

The following list shows all the pages I'd like to improve. Feel free to suggest other improvements and additions in the comments!

- [ ] 1.1 Motivation
- [ ] 1.3 Benefits
- [ ] 3.x Rehydration
- [ ] 3.3 Plugins
- [ ] 3.x devMode vs. production
- [ ] 3.6 Combined Rules / Composing Rules
- [ ] 3.7 Enhancers
- [ ] 4.1 Usage with React (happening with #597)
- [ ] 4.2 Usage with React Native (happening with #597)
- [ ] 4.3 Usage with Preact (happening with #597)
- [ ] 4.4 Usage with Inferno (happening with #597)
- [ ] 4.x Usage with Next
- [ ] 4.x Usage with Gatsby
- [ ] 5.2 Testing Fela Components
- [ ] 5.x Composing Fela Components
- [ ] 5.5 Using ref with React Components (delete with React 16 support)  
- [ ] 11 Thanks

**Comment by houd1ni** [comment]
Please, add vue binding to somewhere https://github.com/houd1ni/fela-vue

**Comment by robinweser** [comment]
Closing in favor of new docs coming soon
